Queskey\FrontEndBundle\Entity\Coursesubjects:
    type: entity
    table: coursesubjects
    indexes:
        courseid:
            columns:
                - courseid
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        subjectname:
            type: string
            nullable: false
            length: 128
            fixed: false
            comment: ''
        subjectdescription:
            type: string
            nullable: true
            length: 512
            fixed: false
            comment: ''
    manyToOne:
        courseid:
            targetEntity: Course
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                courseid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
