Queskey\FrontEndBundle\Entity\Coursetopics:
    type: entity
    table: coursetopics
    indexes:
        subjectid:
            columns:
                - subjectid
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        topicname:
            type: string
            nullable: false
            length: 128
            fixed: false
            comment: ''
        topicdescription:
            type: string
            nullable: false
            length: 512
            fixed: false
            comment: ''
        topictype:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
    manyToOne:
        subjectid:
            targetEntity: Coursesubjects
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                subjectid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
