Queskey\FrontEndBundle\Entity\Courseinnerlessons:
    type: entity
    table: courseinnerlessons
    indexes:
        lessonid:
            columns:
                - lessonid
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        innerlessonname:
            type: string
            nullable: false
            length: 512
            fixed: false
            comment: ''
    manyToOne:
        lessonid:
            targetEntity: Courselessons
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                lessonid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
