Queskey\FrontEndBundle\Entity\Lessoncontents:
    type: entity
    table: lessoncontents
    indexes:
        lessonid:
            columns:
                - lessonid
        innerlessonid:
            columns:
                - innerlessonid
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        content:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    manyToOne:
        lessonid:
            targetEntity: Courselessons
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                lessonid:
                    referencedColumnName: id
            orphanRemoval: false
        innerlessonid:
            targetEntity: Courseinnerlessons
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                innerlessonid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
