Queskey\FrontEndBundle\Entity\Questions:
    type: entity
    table: questions
    indexes:
        topicid:
            columns:
                - topicId
        lessonid:
            columns:
                - lessonId
        dataid:
            columns:
                - dataid
        subjectid:
            columns:
                - subjectId
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        question:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        option1:
            type: string
            nullable: true
            length: 512
            fixed: false
            comment: ''
        option2:
            type: string
            nullable: true
            length: 512
            fixed: false
            comment: ''
        option3:
            type: string
            nullable: true
            length: 512
            fixed: false
            comment: ''
        option4:
            type: string
            nullable: true
            length: 512
            fixed: false
            comment: ''
        option5:
            type: string
            nullable: true
            length: 512
            fixed: false
            comment: ''
        correctoption:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
        solution:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        level:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
    manyToOne:
        topicid:
            targetEntity: Coursetopics
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                topicId:
                    referencedColumnName: id
            orphanRemoval: false
        lessonid:
            targetEntity: Courselessons
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                lessonId:
                    referencedColumnName: id
            orphanRemoval: false
        dataid:
            targetEntity: QuestionData
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                dataid:
                    referencedColumnName: id
            orphanRemoval: false
        subjectid:
            targetEntity: Coursesubjects
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                subjectId:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        quizid:
            targetEntity: Quiz
            cascade: {  }
            mappedBy: questionid
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
