Queskey\FrontEndBundle\Entity\Quiztypes:
    type: entity
    table: quiztypes
    id:
        id:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
